version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: altra
      POSTGRES_USER: altra
      POSTGRES_PASSWORD: altra_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "altra"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ../backend
    env_file:
      - ../backend/.env
    depends_on:
      - db
    volumes:
      - /mnt/interventions:/mnt/interventions:rw
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Monte tes certificats uniquement si tu les as déjà générés sur l'hôte
      # et commente ces deux lignes sinon.
      - certs:/etc/letsencrypt:ro

volumes:
  db_data:
  certs:
